services:
  - type: web
    name: newkoshi-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false        # Set this in Render dashboard
      - key: JWT_SECRET
        sync: false        # Set this in Render dashboard
      - key: FRONTEND_URL
        sync: false        # Set to your Vercel URL e.g. https://newkoshi.vercel.app
